mybatis:
   #mapper.xml type
  typeAliasesPackage: com.example.eleme.pojo
  mapperLocations: com/example/eleme/mapping/*.xml
  
server:
  port: 8668
  
spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/eleme?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8      #serverTimezone=GMT%2B8
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver